#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Feb 22 09:44:18 -03 2020
# SW Build 2700185 on Thu Oct 24 18:45:48 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto ba794e476d74494bbfafd9dc511d86bc --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot multifpga_GT_master_TB_behav xil_defaultlib.multifpga_GT_master_TB -log elaborate.log"
xelab -wto ba794e476d74494bbfafd9dc511d86bc --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot multifpga_GT_master_TB_behav xil_defaultlib.multifpga_GT_master_TB -log elaborate.log

