#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Feb 22 09:45:50 -03 2020
# SW Build 2700185 on Thu Oct 24 18:45:48 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim multifpga_GT_master_TB_behav -key {Behavioral:sim_1:Functional:multifpga_GT_master_TB} -tclbatch multifpga_GT_master_TB.tcl -log simulate.log"
xsim multifpga_GT_master_TB_behav -key {Behavioral:sim_1:Functional:multifpga_GT_master_TB} -tclbatch multifpga_GT_master_TB.tcl -log simulate.log

